{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    {{- include "owlpane-demo.labels" . | nindent 4 }}
    owlpane.dev/demo-workloads: "true"
{{- end }}
