{{- if .Values.appSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecret.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "owlpane-demo.labels" . | nindent 4 }}
  annotations:
    {{- include "owlpane-demo.helmAnnotations" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: demo-placeholder-not-for-production
  {{- if .Values.databases.postgres.enabled }}
  databaseUrl: postgres://{{ .Values.databases.postgres.username }}:{{ .Values.databases.postgres.password }}@{{ .Values.databases.postgres.serviceName }}:{{ .Values.databases.postgres.port }}/{{ .Values.databases.postgres.database }}
  {{- end }}
{{- end }}
