apiVersion: v1
kind: Service
metadata:
  name: demo-storefront
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-storefront
    {{- include "owlpane-demo.labels" . | nindent 4 }}
  annotations:
    {{- include "owlpane-demo.helmAnnotations" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: demo-storefront
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-api
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-api
    {{- include "owlpane-demo.labels" . | nindent 4 }}
  annotations:
    {{- include "owlpane-demo.helmAnnotations" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: demo-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
{{- if .Values.publicService.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.publicService.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: demo-storefront
    {{- include "owlpane-demo.labels" . | nindent 4 }}
  annotations:
    {{- include "owlpane-demo.helmAnnotations" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app: demo-storefront
  ports:
    - name: http
      port: 80
      targetPort: 8080
{{- end }}
